services:
  - type: web
    name: mlflow-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: http://localhost:5000
    autoDeploy: true